### ISSUE TITLE
SSLyze 2.1.4 (from pip) doesn't work with Python 3.6.8

### ISSUE THREAD

**Issue by sskras** [nabla-c0d3/sslyze#509]
**Describe the bug**
SSLyze from pip does not work with Python 3.6.8

**To Reproduce**
1. Install Python 3.
2. Install SSLyze using pip:
```
$ python3 -m sslyze --version
2.1.4
```
3. Run the following command: `python3 api_sample.py`
4. See error:
```
Traceback (most recent call last):
  File "api_sample.py", line 1, in <module>
    from sslyze import (
ImportError: cannot import name 'ServerNetworkLocationViaDirectConnection'
```

**Expected behavior**
The script sample should start. Or maybe at least tell that the SSLyze version is outdated.

**Python environment:**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Python version: Python 3.6.8

**Comment by nabla-c0d3** [comment]
The versions of Python that are currently supported are at the top of the README, displayed as badges. Older versions of Python or SSLyze are no longer supported.
