### PR TITLE
[WIP] Server cipher suite preference list

### PR DESCRIPTION
**Pull request by c0r0n3r**

### CODE REVIEW

**Comment by itlabitto** [comment]
I couldn't manage to make it work in version 1.1.4 by updating the original "openssl_cipher_suites_plugin.py" with your changes, result on error:
"RuntimeError: Scan command failed: [' * TLSV1_2 Cipher Suites:', 'Unhandled exception while running --tlsv1_2:', "AttributeError - 'HTTPSConnection' object has no attribute 'set_cipher_list'"]"
Is there any other changes needed? Any example of the API call working? Thank you.
