### ISSUE TITLE
exceptions.AttributeError - 'NoneType' object has no attribute 'verify'

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/sslyze#87]
python sslyze.py --certinfo=basic ownme.ipredator.se:10000

**Comment by tam7t** [comment]
This command works in 0.11, it looks like the error was introduce in https://github.com/nabla-c0d3/sslyze/commit/375d103326c9e419b487a493747c55f48f9997ac. `ocsp_response.verify` is called when it is `None`.

**Comment by nabla-c0d3** [comment]
Thanks!
